# Generated by Django 5.0.6 on 2024-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proyecto", "0002_alter_miuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miuser",
            name="edad",
            field=models.IntegerField(max_length=3),
        ),
    ]
